version: '3'
services:
  mongo:
    build:
      context: ./mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8000
    depends_on:
      - mongo
    networks:
      - mynetwork
volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge