version: '3'
services:

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo/mongo_data:/data/db
    networks:
      - mynetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8000
    depends_on:
      - mongo
    networks:
      - mynetwork
volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge
